language: go
go:
    - 1.13.x
addons:
    postgresql: '9.6'
services:
    - postgresql
before_script:
    - 'psql -c ''create database golangjobs;'' -U postgres'
    - 'make init'
os:
    - linux
dist: xenial
env:
    - GO111MODULE=off
script:
    - 'make test'
