language: go
go:
    - 1.13.x
addons:
    postgresql: '9.6'
services:
    - postgresql
before_script:
    - 'psql -c ''create database golangjobs;'' -U postgres'
    - 'go get -v github.com/rubenv/sql-migrate/...'
    - 'go get github.com/golang/mock/mockgen'
    - 'go get -u github.com/go-swagger/go-swagger/cmd/swagger'
os:
    - linux
dist: xenial
env:
    - GO111MODULE=on
script:
    - 'go get -t -v ./...'
    - 'go test -v -race ./...'
