language: go
go:
    - 1.13.x
addons:
    postgresql: '9.6'
services:
    - postgresql
before_script:
    - 'make init'
os:
    - linux
dist: xenial
env:
    - GO111MODULE=on
script:
    - 'make test'
