[[override]]
  name = "github.com/posener/complete"
  branch = "v1"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/jinzhu/configor"

[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.2.6"

[[constraint]]
  name = "github.com/labstack/gommon"
  version = "0.2.3"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "gopkg.in/go-playground/validator.v9"
  version = "9.11.0"

[prune]
  go-tests = true
  unused-packages = true
